name = "osmosis-website-preview"
compatibility_date = "2026-02-10"
workers_dev = true

[assets]
directory = "./_site"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "preview.osmosiscast.com"
custom_domain = true
