name = "osmosis-website"
compatibility_date = "2026-02-10"
workers_dev = false

[assets]
directory = "./public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "osmosiscast.com"
custom_domain = true
override_existing_dns_record = true

[[routes]]
pattern = "www.osmosiscast.com"
custom_domain = true
override_existing_dns_record = true
